output_dir: 'experiments/output'
log_dir: 'experiments/log'
device: 'cpu'
dataset:
  name: 'nuua'
  root: 'data/nuua'
  augmentation:
    horizontal_flip: True
    vertial_flip: False
    random_rotation: 30
  train_set: 'train'
  test_set: 'test'

model:
  base: 'densenet_161'
  pretrained: True
  num_output: 2
  image_size: (224,224)
  map_size: 14
  smoothing: True

train:
  batch_size: 32
  optimizer: 'adam'
  lr: 0.001
  num_epochs: 100
  loss:
    beta: 0.5

