output_dir: 'experiments/output'
log_dir: 'experiments/log'
device: 'gpu'
dataset:
  name: 'rose'
  root: 'data/rose'
  augmentation:
    horizontal_flip: True
    vertial_flip: False
    random_rotation: 30
  train_set: 'train.csv'
  test_set: 'test.csv'
  mean: (0.5,0.5,0.5) 
  sigma: (0.5,0.5,0.5)

model:
  base: 'densenet_161'
  pretrained: True
  num_output: 2
  image_size: (224,224)
  map_size: 14
  smoothing: True

train:
  batch_size: 24
  optimizer: 'adam'
  lr: 0.001
  num_epochs: 10
  loss:
    beta: 0.5

test:
  batch_size: 24
  score_type: 'pixel' # types = (pixel, binary, combined)